### ISSUE TITLE
Switch from ino to Arturo for Arduino 1.6.1+ or older

### ISSUE THREAD

**Issue by ryanvade** [marcelocorreia/mcduino#3]
Hello, 

Ino development has stalled. There is a fork which will have support for Arduino 1.6+ called Arturo
https://github.com/scottdarch/Arturo

I really like this plugin but future development will require moving from ino.

**Comment by mcpanthacorp** [comment]
Thanks for the tip, I'll check it out.

**Comment by mcpanthacorp** [comment]
Hi Ryan,
I have tested setting my executable pointing to Ano (Arturo), and works fine. (haven't tried Arduino 1.5+ yet)
As Arturo takes the same commands as Ino.
I will proceed moving to Arturo.
Thanks for the tip.

**Comment by ryanvade** [comment]
Awesome! Thanks for looking into this.  Hopefully Arturo is updated to support 1.6+ soon.
